var SocketEvent = (function () {
    function SocketEvent() {
    }
    SocketEvent.ON_SOCKET_CONNECTED = "ON_SOCKET_CONNECTED";
    SocketEvent.ON_SOCKET_DISCONNECTED = "ON_SOCKET_DISCONNECTED";
    SocketEvent.ON_AUTH_COMPLETE = "ON_AUTH_COMPLETE";
    SocketEvent.ON_PUBLISHER_STOPPED = "ON_PUBLISHER_STOPPED";
    SocketEvent.ON_PUBLISHER_FINISHED = "ON_PUBLISHER_FINISHED";
    SocketEvent.ON_TOTAL_PARTICIPANTS_CHANGED = "ON_TOTAL_PARTICIPANTS_CHANGED";
    SocketEvent.PARTICIPANT_ALREADY_EXISTS = "PARTICIPANT_ALREADY_EXISTS";
    SocketEvent.ON_SUBSCRIBER_ADDED = "ON_SUBSCRIBER_ADDED";
    SocketEvent.ON_SUBSCRIBER_REMOVED = "ON_SUBSCRIBER_REMOVED";
    SocketEvent.ON_PUBLISHER_VIDEO_STATE_CHANGED = "ON_PUBLISHER_VIDEO_STATE_CHANGED";
    SocketEvent.ON_CALL_REQUEST = "ON_CALL_REQUEST";
    SocketEvent.ON_CALL_REQUEST_TIMED_OUT = "ON_CALL_REQUEST_TIMED_OUT";
    SocketEvent.ON_CALL_APPLIED = "ON_CALL_APPLIED";
    SocketEvent.ON_CALL_REJECTED = "ON_CALL_REJECTED";
    SocketEvent.ON_CALL_CANCELED = "ON_CALL_CANCELED";
    SocketEvent.ON_CALL_TERMINATED_BY_CALLER = "ON_CALL_TERMINATED_BY_CALLER";
    SocketEvent.ON_CALL_TERMINATED_BY_PUBLISHER = "ON_CALL_TERMINATED_BY_PUBLISHER";
    SocketEvent.ON_ROOM_BUZY = "ON_ROOM_BUZY";
    SocketEvent.ON_ROOM_NOT_BUZY = "ON_ROOM_NOT_BUZY";
    SocketEvent.ON_CALLS_AVAILABILITY_CHANGED = "ON_CALLS_AVAILABILITY_CHANGED";
    SocketEvent.ROOM_NOT_EXISTS = "ROOM_NOT_EXISTS";
    SocketEvent.ROOM_STATE_ERROR = "ROOM_STATE_ERROR";
    SocketEvent.CONNECTION_ERROR = "CONNECTION_ERROR";
    SocketEvent.CONNECTION_PAUSED = "CONNECTION_PAUSED";
    return SocketEvent;
}());
//# sourceMappingURL=SocketEvent.js.map